apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  labels:
    app: simple-web-app
spec:
  type: LoadBalancer
  selector:
    app: simple-web-app
  ports:
  - name: web
    port: 9000
  
  